#!/usr/bin/env bash
# Writes git SHA + QA log flag into gitignored PulseFillReleaseOverrides.xcconfig, then archives Release.
# Run from anywhere:  bash scripts/archive-testflight.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_ROOT="$ROOT/ios/PulseFill"
OVERRIDE="$IOS_ROOT/Config/PulseFillReleaseOverrides.xcconfig"

REV="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

if [[ -f "$OVERRIDE" ]]; then
  { grep -vE '^(PULSEFILL_SOURCE_REVISION|PULSEFILL_AUTH_QA_LOGS)[[:space:]]*=' "$OVERRIDE" || true; } >"${OVERRIDE}.new"
  mv "${OVERRIDE}.new" "$OVERRIDE"
else
  printf '%s\n' "// Generated by scripts/archive-testflight.sh — add PULSEFILL_SUPABASE_ANON_KEY and other secrets here." >"$OVERRIDE"
fi

{
  echo "PULSEFILL_SOURCE_REVISION = $REV"
  echo "PULSEFILL_AUTH_QA_LOGS = YES"
} >>"$OVERRIDE"

echo "Stamped $OVERRIDE with PULSEFILL_SOURCE_REVISION=$REV and PULSEFILL_AUTH_QA_LOGS=YES"

cd "$IOS_ROOT"
mkdir -p build
xcodebuild \
  -scheme PulseFill \
  -configuration Release \
  -destination 'generic/platform=iOS' \
  -archivePath "$IOS_ROOT/build/PulseFill.xcarchive" \
  clean archive
